services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sipa-app
    container_name: sipa-app
    restart: unless-stopped
    # ports:
    #   - "8000:80"
    volumes:
      - .:/var/www/html # Sinkronisasi folder lokal lu ke dalam container (Live Reload)
    depends_on:
      - db
    networks:
      - default
      - proxy-tier

  db:
    image: mysql:8.0
    container_name: sipa-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # (Ini buat password akun root)
      MYSQL_USER: ${DB_USERNAME}        # (Ini WAJIB ditambahin biar user 'tatan' kebuat)
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - sipa-mysql-data:/var/lib/mysql # Biar data DB gak hilang pas container dimatiin
    networks:
      - default

volumes:
  sipa-mysql-data:

networks:
  proxy-tier:
    external: true